version: '3'

services:
  app:
    build: .
    container_name: reddit_trend_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    depends_on:
      - mongodb
    networks:
      - reddit_trend_network

  mongodb:
    image: mongo:latest
    container_name: reddit_trend_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reddit_trend_network

networks:
  reddit_trend_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
